# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8082
  servlet:
    context-path: /firstDemo

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    test-on-borrow: false
    time-between-eviction-runs-millis: 30000
    log-abandoned: true
    remove-abandoned: true
    validationQuery: SELECT 1
    sql-script-encoding: UTF-8
    continue-on-error: false

  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp