server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8082
  servlet:
    context-path: /demo
  ssl:
    client-auth:

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    testWhileIdle: true
    test-on-borrow: false
    time-between-eviction-runs-millis: 30000
    log-abandoned: true
    remove-abandoned: true
    validationQuery: SELECT 1
    sql-script-encoding: UTF-8
    continue-on-error: false
config:
  jwt:
    # 加密密钥
    secret: abcdefg1234567
    # token有效时长
    expire: 3600
    # header 名称
    header: token
